import { useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { ExternalLink, ShieldAlert, TerminalSquare } from "lucide-react";
import { AppShell } from "@/components/layout/app-shell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type Signal={level:"review"|"caution";title:string;detail:string};
type Review={repository:{full_name:string;html_url:string;description:string|null;default_branch:string;created_at:string;updated_at:string;archived:boolean;fork:boolean;stargazers_count:number;forks_count:number;open_issues_count:number;license:string|null};readme:{path:string;content:string}|null;files:{path:string;type:string}[];workflows:{path:string;type:string}[];manifests:{path:string;type:string}[];signals:Signal[];checked_at:string};
export const Route=createFileRoute("/github-reading-room")({component:GitHubReadingRoom});

function GitHubReadingRoom(){
 const [query,setQuery]=useState("POWDER-RANGER/CivilianIntelligence");
 const [result,setResult]=useState<Review|null>(null);
 const [loading,setLoading]=useState(false);
 const [error,setError]=useState("");
 async function inspect(){
  setLoading(true);setError("");
  try{const response=await fetch("/api/civint/github/repository?repo="+encodeURIComponent(query.trim()));const data=await response.json();if(!response.ok)throw new Error(data.message??"Repository inspection unavailable");setResult(data as Review);}
  catch(err){setError(err instanceof Error?err.message:"Repository inspection unavailable");}
  finally{setLoading(false);}
 }
 return <AppShell><div className="mx-auto w-full max-w-6xl px-4 py-8">
  <div className="max-w-3xl"><p className="font-mono text-[10px] uppercase tracking-[0.22em] text-muted-foreground">Technical reading room</p><h1 className="mt-2 font-display text-4xl md:text-5xl">GitHub Reading Room</h1><p className="mt-3 text-sm leading-relaxed text-muted-foreground">Learn how to inspect a repository before downloading, installing, or executing anything from it. CIVINT reads public metadata and selected text files; it never executes repository code.</p></div>
  <section className="mt-6 rounded-2xl border border-border bg-card p-5 shadow-sm"><div className="flex flex-col gap-3 md:flex-row"><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="github.com/owner/repository" aria-label="GitHub repository" onKeyDown={e=>{if(e.key==="Enter")void inspect();}}/><Button onClick={()=>void inspect()} disabled={loading||!query.trim()}>{loading?"Inspecting…":"Inspect repository"}</Button></div><p className="mt-3 text-[11px] text-muted-foreground">Public metadata only. No GitHub account access, dependency installation, binary execution, or local Action execution.</p></section>
  {error&&<div className="mt-4 rounded-xl border border-border bg-card p-4 text-sm text-muted-foreground">{error}</div>}
  {result?<><section className="mt-6 rounded-2xl border border-border bg-card p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-display text-2xl">{result.repository.full_name}</h2>{result.repository.archived&&<Badge variant="outline">archived</Badge>}{result.repository.fork&&<Badge variant="outline">fork</Badge>}</div><p className="mt-2 max-w-3xl text-sm text-muted-foreground">{result.repository.description??"No repository description."}</p></div><a href={result.repository.html_url} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1.5 text-sm font-medium text-primary hover:underline">Open on GitHub <ExternalLink className="size-3.5"/></a></div>
   <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[[ "Default branch",result.repository.default_branch ],[ "Created",new Date(result.repository.created_at).toLocaleDateString() ],[ "Updated",new Date(result.repository.updated_at).toLocaleDateString() ],[ "License",result.repository.license??"Not declared" ],[ "Stars",result.repository.stargazers_count.toLocaleString() ],[ "Forks",result.repository.forks_count.toLocaleString() ],[ "Open issues",result.repository.open_issues_count.toLocaleString() ],[ "Checked",new Date(result.checked_at).toLocaleString() ]].map(([label,value])=><div key={label} className="rounded-lg border border-border bg-background p-3"><p className="font-mono text-[9px] uppercase tracking-wider text-muted-foreground">{label}</p><p className="mt-1 text-sm">{value}</p></div>)}</div>
  </section>
  <section className="mt-6 grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center gap-2"><ShieldAlert className="size-4 text-primary"/><h2 className="font-display text-2xl">Review signals</h2></div><p className="mt-1 text-xs text-muted-foreground">Inspection prompts, not malware verdicts. A signal means “look closer.”</p><div className="mt-4 space-y-3">{result.signals.length?result.signals.map(signal=><div key={signal.title} className="rounded-xl border border-border p-4"><div className="flex items-center justify-between gap-3"><p className="text-sm font-medium">{signal.title}</p><Badge variant={signal.level==="review"?"warn":"outline"}>{signal.level}</Badge></div><p className="mt-2 text-xs leading-relaxed text-muted-foreground">{signal.detail}</p></div>):<div className="rounded-xl border border-border p-4 text-sm text-muted-foreground">No configured review signals fired. That is not a safety guarantee.</div>}</div></div>
  <div className="rounded-2xl border border-border bg-card p-5"><div className="flex items-center gap-2"><TerminalSquare className="size-4 text-primary"/><h2 className="font-display text-2xl">Where to look</h2></div><div className="mt-4 space-y-3">{[[ "README",result.readme?"Read what the project says it does, then compare that claim with installation instructions.":"No README returned." ],[ "Workflows",result.workflows.length?result.workflows.length+" workflow file(s) found. Inspect what GitHub Actions executes.":"No workflow files detected." ],[ "Manifests",result.manifests.length?result.manifests.length+" common dependency/build manifest(s) found.":"No common manifest detected." ],[ "Repository files",result.files.length+" top-level items returned. Start with install scripts, build files, and executable assets." ]].map(([title,body])=><div key={title} className="rounded-xl border border-border p-4"><p className="font-medium">{title}</p><p className="mt-1 text-xs leading-relaxed text-muted-foreground">{body}</p></div>)}</div></div></section>
  <section className="mt-6 rounded-2xl border border-border bg-background p-5"><h2 className="font-display text-2xl">Beginner’s inspection sequence</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{[[ "1. Ownership","Who publishes it? Is the owner an established project, organization, or maintainer?" ],[ "2. History","Check age, commits, contributors, releases, and recent changes. A known repository can still change hands." ],[ "3. Installation","Treat every command in the README as code. Do not paste commands you do not understand into a terminal." ],[ "4. Automation","Open .github/workflows and inspect commands, downloads, secrets, and permissions." ],[ "5. Dependencies","Read dependency manifests and install scripts. Watch for unexpected external sources." ],[ "6. Releases","Prefer known releases, checksums, and reproducible build instructions when available." ],[ "7. External connections","Look for downloads, installers, webhooks, and privilege escalation." ],[ "8. Decide","CIVINT does not certify software. When evidence is unclear, do not run it on a trusted device." ]].map(([title,body])=><div key={title} className="rounded-xl border border-border bg-card p-4"><p className="text-sm font-medium">{title}</p><p className="mt-1 text-xs leading-relaxed text-muted-foreground">{body}</p></div>)}</div></section>
 </>:<section className="mt-6 rounded-2xl border border-border bg-card p-6"><h2 className="font-display text-2xl">Start with a repository</h2><p className="mt-2 max-w-2xl text-sm leading-relaxed text-muted-foreground">CIVINT shows public metadata and the parts of a repository that are most important to inspect. It does not execute binaries, install dependencies, or treat heuristics as proof of maliciousness.</p></section>}
  <p className="mt-6 text-xs text-muted-foreground"><Link to="/sources" className="text-primary hover:underline">Inspect CIVINT source registry</Link>{" · "}The Reading Room is an inspection aid, not a security certification service.</p>
 </div></AppShell>
}