/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as MovementRouteImport } from './routes/movement'
import { Route as OversightRouteImport } from './routes/oversight'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ToolkitRouteImport } from './routes/toolkit'
import { Route as VeilRouteImport } from './routes/veil'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const MovementRoute = MovementRouteImport.update({
  id: '/movement',
  path: '/movement',
  getParentRoute: () => rootRouteImport,
} as any)
const OversightRoute = OversightRouteImport.update({
  id: '/oversight',
  path: '/oversight',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolkitRoute = ToolkitRouteImport.update({
  id: '/toolkit',
  path: '/toolkit',
  getParentRoute: () => rootRouteImport,
} as any)
const VeilRoute = VeilRouteImport.update({
  id: '/veil',
  path: '/veil',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/finance': typeof FinanceRoute
  '/movement': typeof MovementRoute
  '/oversight': typeof OversightRoute
  '/privacy': typeof PrivacyRoute
  '/toolkit': typeof ToolkitRoute
  '/veil': typeof VeilRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/finance': typeof FinanceRoute
  '/movement': typeof MovementRoute
  '/oversight': typeof OversightRoute
  '/privacy': typeof PrivacyRoute
  '/toolkit': typeof ToolkitRoute
  '/veil': typeof VeilRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/finance': typeof FinanceRoute
  '/movement': typeof MovementRoute
  '/oversight': typeof OversightRoute
  '/privacy': typeof PrivacyRoute
  '/toolkit': typeof ToolkitRoute
  '/veil': typeof VeilRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/finance'
    | '/movement'
    | '/oversight'
    | '/privacy'
    | '/toolkit'
    | '/veil'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/finance'
    | '/movement'
    | '/oversight'
    | '/privacy'
    | '/toolkit'
    | '/veil'
  id:
    | '__root__'
    | '/'
    | '/finance'
    | '/movement'
    | '/oversight'
    | '/privacy'
    | '/toolkit'
    | '/veil'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FinanceRoute: typeof FinanceRoute
  MovementRoute: typeof MovementRoute
  OversightRoute: typeof OversightRoute
  PrivacyRoute: typeof PrivacyRoute
  ToolkitRoute: typeof ToolkitRoute
  VeilRoute: typeof VeilRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movement': {
      id: '/movement'
      path: '/movement'
      fullPath: '/movement'
      preLoaderRoute: typeof MovementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oversight': {
      id: '/oversight'
      path: '/oversight'
      fullPath: '/oversight'
      preLoaderRoute: typeof OversightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toolkit': {
      id: '/toolkit'
      path: '/toolkit'
      fullPath: '/toolkit'
      preLoaderRoute: typeof ToolkitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veil': {
      id: '/veil'
      path: '/veil'
      fullPath: '/veil'
      preLoaderRoute: typeof VeilRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FinanceRoute: FinanceRoute,
  MovementRoute: MovementRoute,
  OversightRoute: OversightRoute,
  PrivacyRoute: PrivacyRoute,
  ToolkitRoute: ToolkitRoute,
  VeilRoute: VeilRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
