/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as GithubReadingRoomRouteImport } from './routes/github-reading-room'
import { Route as MovementRouteImport } from './routes/movement'
import { Route as OversightRouteImport } from './routes/oversight'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReadingRoomRouteImport } from './routes/reading-room'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as SignalRouteImport } from './routes/signal'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as TitanRouteImport } from './routes/titan'
import { Route as ToolkitRouteImport } from './routes/toolkit'
import { Route as VeilRouteImport } from './routes/veil'
import { Route as WatchtowerRouteImport } from './routes/watchtower'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as RecordsIdRouteImport } from './routes/records.$id'
import { Route as ApiCivintSourcesRouteImport } from './routes/api/civint/sources'
import { Route as ApiCivintAlprDataRouteImport } from './routes/api/civint/alpr/data'
import { Route as ApiCivintFinanceFederalRouteImport } from './routes/api/civint/finance/federal'
import { Route as ApiCivintFinanceSecRouteImport } from './routes/api/civint/finance/sec'
import { Route as ApiCivintGithubRepositoryRouteImport } from './routes/api/civint/github/repository'
import { Route as ApiCivintLegislationCongressRouteImport } from './routes/api/civint/legislation/congress'
import { Route as ApiCivintLocationContextRouteImport } from './routes/api/civint/location/context'
import { Route as ApiCivintOversightFoiaRouteImport } from './routes/api/civint/oversight/foia'
import { Route as ApiCivintReadingRoomSourceRouteImport } from './routes/api/civint/reading-room/source'
import { Route as ApiCivintRecordsIdRouteImport } from './routes/api/civint/records/$id'
import { Route as ApiCivintRecordsSearchRouteImport } from './routes/api/civint/records/search'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubReadingRoomRoute = GithubReadingRoomRouteImport.update({
  id: '/github-reading-room',
  path: '/github-reading-room',
  getParentRoute: () => rootRouteImport,
} as any)
const MovementRoute = MovementRouteImport.update({
  id: '/movement',
  path: '/movement',
  getParentRoute: () => rootRouteImport,
} as any)
const OversightRoute = OversightRouteImport.update({
  id: '/oversight',
  path: '/oversight',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadingRoomRoute = ReadingRoomRouteImport.update({
  id: '/reading-room',
  path: '/reading-room',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalRoute = SignalRouteImport.update({
  id: '/signal',
  path: '/signal',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const TitanRoute = TitanRouteImport.update({
  id: '/titan',
  path: '/titan',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolkitRoute = ToolkitRouteImport.update({
  id: '/toolkit',
  path: '/toolkit',
  getParentRoute: () => rootRouteImport,
} as any)
const VeilRoute = VeilRouteImport.update({
  id: '/veil',
  path: '/veil',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchtowerRoute = WatchtowerRouteImport.update({
  id: '/watchtower',
  path: '/watchtower',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsIdRoute = RecordsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RecordsRoute,
} as any)
const ApiCivintSourcesRoute = ApiCivintSourcesRouteImport.update({
  id: '/api/civint/sources',
  path: '/api/civint/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCivintAlprDataRoute = ApiCivintAlprDataRouteImport.update({
  id: '/api/civint/alpr/data',
  path: '/api/civint/alpr/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCivintFinanceFederalRoute = ApiCivintFinanceFederalRouteImport.update({
  id: '/api/civint/finance/federal',
  path: '/api/civint/finance/federal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCivintFinanceSecRoute = ApiCivintFinanceSecRouteImport.update({
  id: '/api/civint/finance/sec',
  path: '/api/civint/finance/sec',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCivintGithubRepositoryRoute =
  ApiCivintGithubRepositoryRouteImport.update({
    id: '/api/civint/github/repository',
    path: '/api/civint/github/repository',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCivintLegislationCongressRoute =
  ApiCivintLegislationCongressRouteImport.update({
    id: '/api/civint/legislation/congress',
    path: '/api/civint/legislation/congress',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCivintLocationContextRoute =
  ApiCivintLocationContextRouteImport.update({
    id: '/api/civint/location/context',
    path: '/api/civint/location/context',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCivintOversightFoiaRoute = ApiCivintOversightFoiaRouteImport.update({
  id: '/api/civint/oversight/foia',
  path: '/api/civint/oversight/foia',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCivintReadingRoomSourceRoute =
  ApiCivintReadingRoomSourceRouteImport.update({
    id: '/api/civint/reading-room/source',
    path: '/api/civint/reading-room/source',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCivintRecordsIdRoute = ApiCivintRecordsIdRouteImport.update({
  id: '/api/civint/records/$id',
  path: '/api/civint/records/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCivintRecordsSearchRoute = ApiCivintRecordsSearchRouteImport.update({
  id: '/api/civint/records/search',
  path: '/api/civint/records/search',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/finance': typeof FinanceRoute
  '/github-reading-room': typeof GithubReadingRoomRoute
  '/movement': typeof MovementRoute
  '/oversight': typeof OversightRoute
  '/privacy': typeof PrivacyRoute
  '/reading-room': typeof ReadingRoomRoute
  '/records': typeof RecordsRouteWithChildren
  '/signal': typeof SignalRoute
  '/sources': typeof SourcesRoute
  '/titan': typeof TitanRoute
  '/toolkit': typeof ToolkitRoute
  '/veil': typeof VeilRoute
  '/watchtower': typeof WatchtowerRoute
  '/api/health': typeof ApiHealthRoute
  '/records/$id': typeof RecordsIdRoute
  '/api/civint/sources': typeof ApiCivintSourcesRoute
  '/api/civint/alpr/data': typeof ApiCivintAlprDataRoute
  '/api/civint/finance/federal': typeof ApiCivintFinanceFederalRoute
  '/api/civint/finance/sec': typeof ApiCivintFinanceSecRoute
  '/api/civint/github/repository': typeof ApiCivintGithubRepositoryRoute
  '/api/civint/legislation/congress': typeof ApiCivintLegislationCongressRoute
  '/api/civint/location/context': typeof ApiCivintLocationContextRoute
  '/api/civint/oversight/foia': typeof ApiCivintOversightFoiaRoute
  '/api/civint/reading-room/source': typeof ApiCivintReadingRoomSourceRoute
  '/api/civint/records/$id': typeof ApiCivintRecordsIdRoute
  '/api/civint/records/search': typeof ApiCivintRecordsSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/finance': typeof FinanceRoute
  '/github-reading-room': typeof GithubReadingRoomRoute
  '/movement': typeof MovementRoute
  '/oversight': typeof OversightRoute
  '/privacy': typeof PrivacyRoute
  '/reading-room': typeof ReadingRoomRoute
  '/records': typeof RecordsRouteWithChildren
  '/signal': typeof SignalRoute
  '/sources': typeof SourcesRoute
  '/titan': typeof TitanRoute
  '/toolkit': typeof ToolkitRoute
  '/veil': typeof VeilRoute
  '/watchtower': typeof WatchtowerRoute
  '/api/health': typeof ApiHealthRoute
  '/records/$id': typeof RecordsIdRoute
  '/api/civint/sources': typeof ApiCivintSourcesRoute
  '/api/civint/alpr/data': typeof ApiCivintAlprDataRoute
  '/api/civint/finance/federal': typeof ApiCivintFinanceFederalRoute
  '/api/civint/finance/sec': typeof ApiCivintFinanceSecRoute
  '/api/civint/github/repository': typeof ApiCivintGithubRepositoryRoute
  '/api/civint/legislation/congress': typeof ApiCivintLegislationCongressRoute
  '/api/civint/location/context': typeof ApiCivintLocationContextRoute
  '/api/civint/oversight/foia': typeof ApiCivintOversightFoiaRoute
  '/api/civint/reading-room/source': typeof ApiCivintReadingRoomSourceRoute
  '/api/civint/records/$id': typeof ApiCivintRecordsIdRoute
  '/api/civint/records/search': typeof ApiCivintRecordsSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/finance': typeof FinanceRoute
  '/github-reading-room': typeof GithubReadingRoomRoute
  '/movement': typeof MovementRoute
  '/oversight': typeof OversightRoute
  '/privacy': typeof PrivacyRoute
  '/reading-room': typeof ReadingRoomRoute
  '/records': typeof RecordsRouteWithChildren
  '/signal': typeof SignalRoute
  '/sources': typeof SourcesRoute
  '/titan': typeof TitanRoute
  '/toolkit': typeof ToolkitRoute
  '/veil': typeof VeilRoute
  '/watchtower': typeof WatchtowerRoute
  '/api/health': typeof ApiHealthRoute
  '/records/$id': typeof RecordsIdRoute
  '/api/civint/sources': typeof ApiCivintSourcesRoute
  '/api/civint/alpr/data': typeof ApiCivintAlprDataRoute
  '/api/civint/finance/federal': typeof ApiCivintFinanceFederalRoute
  '/api/civint/finance/sec': typeof ApiCivintFinanceSecRoute
  '/api/civint/github/repository': typeof ApiCivintGithubRepositoryRoute
  '/api/civint/legislation/congress': typeof ApiCivintLegislationCongressRoute
  '/api/civint/location/context': typeof ApiCivintLocationContextRoute
  '/api/civint/oversight/foia': typeof ApiCivintOversightFoiaRoute
  '/api/civint/reading-room/source': typeof ApiCivintReadingRoomSourceRoute
  '/api/civint/records/$id': typeof ApiCivintRecordsIdRoute
  '/api/civint/records/search': typeof ApiCivintRecordsSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/finance'
    | '/github-reading-room'
    | '/movement'
    | '/oversight'
    | '/privacy'
    | '/reading-room'
    | '/records'
    | '/signal'
    | '/sources'
    | '/titan'
    | '/toolkit'
    | '/veil'
    | '/watchtower'
    | '/api/health'
    | '/records/$id'
    | '/api/civint/sources'
    | '/api/civint/alpr/data'
    | '/api/civint/finance/federal'
    | '/api/civint/finance/sec'
    | '/api/civint/github/repository'
    | '/api/civint/legislation/congress'
    | '/api/civint/location/context'
    | '/api/civint/oversight/foia'
    | '/api/civint/reading-room/source'
    | '/api/civint/records/$id'
    | '/api/civint/records/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/finance'
    | '/github-reading-room'
    | '/movement'
    | '/oversight'
    | '/privacy'
    | '/reading-room'
    | '/records'
    | '/signal'
    | '/sources'
    | '/titan'
    | '/toolkit'
    | '/veil'
    | '/watchtower'
    | '/api/health'
    | '/records/$id'
    | '/api/civint/sources'
    | '/api/civint/alpr/data'
    | '/api/civint/finance/federal'
    | '/api/civint/finance/sec'
    | '/api/civint/github/repository'
    | '/api/civint/legislation/congress'
    | '/api/civint/location/context'
    | '/api/civint/oversight/foia'
    | '/api/civint/reading-room/source'
    | '/api/civint/records/$id'
    | '/api/civint/records/search'
  id:
    | '__root__'
    | '/'
    | '/finance'
    | '/github-reading-room'
    | '/movement'
    | '/oversight'
    | '/privacy'
    | '/reading-room'
    | '/records'
    | '/signal'
    | '/sources'
    | '/titan'
    | '/toolkit'
    | '/veil'
    | '/watchtower'
    | '/api/health'
    | '/records/$id'
    | '/api/civint/sources'
    | '/api/civint/alpr/data'
    | '/api/civint/finance/federal'
    | '/api/civint/finance/sec'
    | '/api/civint/github/repository'
    | '/api/civint/legislation/congress'
    | '/api/civint/location/context'
    | '/api/civint/oversight/foia'
    | '/api/civint/reading-room/source'
    | '/api/civint/records/$id'
    | '/api/civint/records/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FinanceRoute: typeof FinanceRoute
  GithubReadingRoomRoute: typeof GithubReadingRoomRoute
  MovementRoute: typeof MovementRoute
  OversightRoute: typeof OversightRoute
  PrivacyRoute: typeof PrivacyRoute
  ReadingRoomRoute: typeof ReadingRoomRoute
  RecordsRoute: typeof RecordsRouteWithChildren
  SignalRoute: typeof SignalRoute
  SourcesRoute: typeof SourcesRoute
  TitanRoute: typeof TitanRoute
  ToolkitRoute: typeof ToolkitRoute
  VeilRoute: typeof VeilRoute
  WatchtowerRoute: typeof WatchtowerRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiCivintSourcesRoute: typeof ApiCivintSourcesRoute
  ApiCivintAlprDataRoute: typeof ApiCivintAlprDataRoute
  ApiCivintFinanceFederalRoute: typeof ApiCivintFinanceFederalRoute
  ApiCivintFinanceSecRoute: typeof ApiCivintFinanceSecRoute
  ApiCivintGithubRepositoryRoute: typeof ApiCivintGithubRepositoryRoute
  ApiCivintLegislationCongressRoute: typeof ApiCivintLegislationCongressRoute
  ApiCivintLocationContextRoute: typeof ApiCivintLocationContextRoute
  ApiCivintOversightFoiaRoute: typeof ApiCivintOversightFoiaRoute
  ApiCivintReadingRoomSourceRoute: typeof ApiCivintReadingRoomSourceRoute
  ApiCivintRecordsIdRoute: typeof ApiCivintRecordsIdRoute
  ApiCivintRecordsSearchRoute: typeof ApiCivintRecordsSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github-reading-room': {
      id: '/github-reading-room'
      path: '/github-reading-room'
      fullPath: '/github-reading-room'
      preLoaderRoute: typeof GithubReadingRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movement': {
      id: '/movement'
      path: '/movement'
      fullPath: '/movement'
      preLoaderRoute: typeof MovementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oversight': {
      id: '/oversight'
      path: '/oversight'
      fullPath: '/oversight'
      preLoaderRoute: typeof OversightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reading-room': {
      id: '/reading-room'
      path: '/reading-room'
      fullPath: '/reading-room'
      preLoaderRoute: typeof ReadingRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signal': {
      id: '/signal'
      path: '/signal'
      fullPath: '/signal'
      preLoaderRoute: typeof SignalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/titan': {
      id: '/titan'
      path: '/titan'
      fullPath: '/titan'
      preLoaderRoute: typeof TitanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toolkit': {
      id: '/toolkit'
      path: '/toolkit'
      fullPath: '/toolkit'
      preLoaderRoute: typeof ToolkitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veil': {
      id: '/veil'
      path: '/veil'
      fullPath: '/veil'
      preLoaderRoute: typeof VeilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchtower': {
      id: '/watchtower'
      path: '/watchtower'
      fullPath: '/watchtower'
      preLoaderRoute: typeof WatchtowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records/$id': {
      id: '/records/$id'
      path: '/$id'
      fullPath: '/records/$id'
      preLoaderRoute: typeof RecordsIdRouteImport
      parentRoute: typeof RecordsRoute
    }
    '/api/civint/sources': {
      id: '/api/civint/sources'
      path: '/api/civint/sources'
      fullPath: '/api/civint/sources'
      preLoaderRoute: typeof ApiCivintSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/civint/alpr/data': {
      id: '/api/civint/alpr/data'
      path: '/api/civint/alpr/data'
      fullPath: '/api/civint/alpr/data'
      preLoaderRoute: typeof ApiCivintAlprDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/civint/finance/federal': {
      id: '/api/civint/finance/federal'
      path: '/api/civint/finance/federal'
      fullPath: '/api/civint/finance/federal'
      preLoaderRoute: typeof ApiCivintFinanceFederalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/civint/finance/sec': {
      id: '/api/civint/finance/sec'
      path: '/api/civint/finance/sec'
      fullPath: '/api/civint/finance/sec'
      preLoaderRoute: typeof ApiCivintFinanceSecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/civint/github/repository': {
      id: '/api/civint/github/repository'
      path: '/api/civint/github/repository'
      fullPath: '/api/civint/github/repository'
      preLoaderRoute: typeof ApiCivintGithubRepositoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/civint/legislation/congress': {
      id: '/api/civint/legislation/congress'
      path: '/api/civint/legislation/congress'
      fullPath: '/api/civint/legislation/congress'
      preLoaderRoute: typeof ApiCivintLegislationCongressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/civint/location/context': {
      id: '/api/civint/location/context'
      path: '/api/civint/location/context'
      fullPath: '/api/civint/location/context'
      preLoaderRoute: typeof ApiCivintLocationContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/civint/oversight/foia': {
      id: '/api/civint/oversight/foia'
      path: '/api/civint/oversight/foia'
      fullPath: '/api/civint/oversight/foia'
      preLoaderRoute: typeof ApiCivintOversightFoiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/civint/reading-room/source': {
      id: '/api/civint/reading-room/source'
      path: '/api/civint/reading-room/source'
      fullPath: '/api/civint/reading-room/source'
      preLoaderRoute: typeof ApiCivintReadingRoomSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/civint/records/$id': {
      id: '/api/civint/records/$id'
      path: '/api/civint/records/$id'
      fullPath: '/api/civint/records/$id'
      preLoaderRoute: typeof ApiCivintRecordsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/civint/records/search': {
      id: '/api/civint/records/search'
      path: '/api/civint/records/search'
      fullPath: '/api/civint/records/search'
      preLoaderRoute: typeof ApiCivintRecordsSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RecordsRouteChildren {
  RecordsIdRoute: typeof RecordsIdRoute
}

const RecordsRouteChildren: RecordsRouteChildren = {
  RecordsIdRoute: RecordsIdRoute,
}

const RecordsRouteWithChildren =
  RecordsRoute._addFileChildren(RecordsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FinanceRoute: FinanceRoute,
  GithubReadingRoomRoute: GithubReadingRoomRoute,
  MovementRoute: MovementRoute,
  OversightRoute: OversightRoute,
  PrivacyRoute: PrivacyRoute,
  ReadingRoomRoute: ReadingRoomRoute,
  RecordsRoute: RecordsRouteWithChildren,
  SignalRoute: SignalRoute,
  SourcesRoute: SourcesRoute,
  TitanRoute: TitanRoute,
  ToolkitRoute: ToolkitRoute,
  VeilRoute: VeilRoute,
  WatchtowerRoute: WatchtowerRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiCivintSourcesRoute: ApiCivintSourcesRoute,
  ApiCivintAlprDataRoute: ApiCivintAlprDataRoute,
  ApiCivintFinanceFederalRoute: ApiCivintFinanceFederalRoute,
  ApiCivintFinanceSecRoute: ApiCivintFinanceSecRoute,
  ApiCivintGithubRepositoryRoute: ApiCivintGithubRepositoryRoute,
  ApiCivintLegislationCongressRoute: ApiCivintLegislationCongressRoute,
  ApiCivintLocationContextRoute: ApiCivintLocationContextRoute,
  ApiCivintOversightFoiaRoute: ApiCivintOversightFoiaRoute,
  ApiCivintReadingRoomSourceRoute: ApiCivintReadingRoomSourceRoute,
  ApiCivintRecordsIdRoute: ApiCivintRecordsIdRoute,
  ApiCivintRecordsSearchRoute: ApiCivintRecordsSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
