// This file is auto-generated by TanStack Router
// Do not edit this file directly

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as VeilImport } from './routes/veil'
import { Route as ToolkitImport } from './routes/toolkit'
import { Route as PrivacyImport } from './routes/privacy'
import { Route as OversightImport } from './routes/oversight'
import { Route as MovementImport } from './routes/movement'
import { Route as FinanceImport } from './routes/finance'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const VeilRoute = VeilImport.update({
  id: '/veil',
  path: '/veil',
  getParentRoute: () => rootRoute,
} as any)

const ToolkitRoute = ToolkitImport.update({
  id: '/toolkit',
  path: '/toolkit',
  getParentRoute: () => rootRoute,
} as any)

const PrivacyRoute = PrivacyImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRoute,
} as any)

const OversightRoute = OversightImport.update({
  id: '/oversight',
  path: '/oversight',
  getParentRoute: () => rootRoute,
} as any)

const MovementRoute = MovementImport.update({
  id: '/movement',
  path: '/movement',
  getParentRoute: () => rootRoute,
} as any)

const FinanceRoute = FinanceImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceImport
      parentRoute: typeof rootRoute
    }
    '/movement': {
      id: '/movement'
      path: '/movement'
      fullPath: '/movement'
      preLoaderRoute: typeof MovementImport
      parentRoute: typeof rootRoute
    }
    '/oversight': {
      id: '/oversight'
      path: '/oversight'
      fullPath: '/oversight'
      preLoaderRoute: typeof OversightImport
      parentRoute: typeof rootRoute
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyImport
      parentRoute: typeof rootRoute
    }
    '/toolkit': {
      id: '/toolkit'
      path: '/toolkit'
      fullPath: '/toolkit'
      preLoaderRoute: typeof ToolkitImport
      parentRoute: typeof rootRoute
    }
    '/veil': {
      id: '/veil'
      path: '/veil'
      fullPath: '/veil'
      preLoaderRoute: typeof VeilImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/finance': typeof FinanceRoute
  '/movement': typeof MovementRoute
  '/oversight': typeof OversightRoute
  '/privacy': typeof PrivacyRoute
  '/toolkit': typeof ToolkitRoute
  '/veil': typeof VeilRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/finance': typeof FinanceRoute
  '/movement': typeof MovementRoute
  '/oversight': typeof OversightRoute
  '/privacy': typeof PrivacyRoute
  '/toolkit': typeof ToolkitRoute
  '/veil': typeof VeilRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/finance': typeof FinanceRoute
  '/movement': typeof MovementRoute
  '/oversight': typeof OversightRoute
  '/privacy': typeof PrivacyRoute
  '/toolkit': typeof ToolkitRoute
  '/veil': typeof VeilRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/finance' | '/movement' | '/oversight' | '/privacy' | '/toolkit' | '/veil'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/finance' | '/movement' | '/oversight' | '/privacy' | '/toolkit' | '/veil'
  id: '__root__' | '/' | '/finance' | '/movement' | '/oversight' | '/privacy' | '/toolkit' | '/veil'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FinanceRoute: typeof FinanceRoute
  MovementRoute: typeof MovementRoute
  OversightRoute: typeof OversightRoute
  PrivacyRoute: typeof PrivacyRoute
  ToolkitRoute: typeof ToolkitRoute
  VeilRoute: typeof VeilRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FinanceRoute: FinanceRoute,
  MovementRoute: MovementRoute,
  OversightRoute: OversightRoute,
  PrivacyRoute: PrivacyRoute,
  ToolkitRoute: ToolkitRoute,
  VeilRoute: VeilRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
